Reference example
Jaseci-Labs/jaclang pull request #125
Opened 2023-12-19 10:31 UTC by kugesan1105

2023-12-19 10:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Jaseci-Labs/jaclang?pullRequest=125) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Jaseci-Labs/jaclang?pullRequest=125) before we can accept your contribution.<br/>**3** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: kugesan1105<br/>:white_check_mark: Saru1999<br/>:white_check_mark: Sivasuthan9<br/>:x: kugesan<br/>:x: SARUJAN KUGATHAS<br/><hr/>**SARUJAN KUGATHAS** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Jaseci-Labs/jaclang?pullRequest=125) it.</sub>

2023-12-19 18:12 UTC, marsninja requested changes
Hi @kugesan1105 and others, one tweak, I like that you use the single comment to identify file names however can we covert to snake case for the files such that `//If statements` would turn into `if_statements.jac` and `if_statements.py` and we dont have files with spaces. We can discuss tomorrow too.

2023-12-19 18:18 UTC, kugesan1105 commented
@marsninja Are we converting all file names with spaces to snake case?

2023-12-21 07:24 UTC, marsninja approved these changes

2023-12-21 07:24 UTC, merged