Grammer checking llm example
Jaseci-Labs/jaclang pull request #356
Opened 2024-05-02 15:02 UTC by TharukaCkasthuri

2024-05-08 15:32 UTC, chandralegend requested changes
Reviews Added

2024-05-08 15:32 UTC, chandralegend commented on examples/genai/gc_app/grammar_checker.jac
> +import:py anthropic;
use `import:py from jaclang.core.llms, Anthropic;`

2024-05-08 15:32 UTC, chandralegend commented on examples/genai/gc_app/grammar_checker.jac
> +can "Correct Text without any  Grammar Errors"
Semstring Should be the Action. In your case use something like "Resolve any grammar errors in the given text"

2024-05-08 15:32 UTC, chandralegend commented on examples/genai/gc_app/grammar_checker.jac
> +correct_grammar(text: 'Text with Errors': str) -> 'Corrected Text': str by grammar_checker( temperature=0.9);
`correct_grammar(text: 'Text with Errors': str) -> 'Grammar Corrected Text': str by llm( temperature=0.9);`

2024-05-08 15:32 UTC, chandralegend commented on examples/genai/gc_app/grammar_checker.jac
> +glob grammar_checker = grammar_checker();
use `llm` instead of `grammar_checker`

2024-05-08 15:33 UTC, chandralegend commented
@TharukaCkasthuri Add a Description to the PR

2024-05-11 11:11 UTC, chandralegend approved these changes

2024-05-11 11:11 UTC, chandralegend commented on examples/genai/gc_app/grammar_checker.jac
> +   with open("fixtures/text.txt", 'r') as file {
move the grammar_checkerjac to genai folder instead nesting in gc_app. Instead of using a .txt file add a function where the user can mention the absolute path of the file in command line.

2024-05-11 11:12 UTC, chandralegend requested changes
move the grammar_checkerjac to genai folder instead nesting in gc_app. Instead of using a .txt file add a function where the user can mention the absolute path of the file in command line.

2024-05-11 11:13 UTC, chandralegend requested changes
Tests are failing because of additional semi colon. Its good practice to run the file and check wether its working before pushing commits

2024-05-11 11:13 UTC, chandralegend commented on examples/genai/gc_app/grammar_checker.jac
> +glob llm = Anthropic(model_name="claude-3-sonnet-20240229");;
Tests are failing because of additional semi colon. Its good practice to run the file and check wether its working before pushing commits

2024-05-15 15:56 UTC, ypkang approved these changes

2024-05-15 15:57 UTC, merged