pluging for streamlit
Jaseci-Labs/jaclang pull request #379
Opened 2024-05-15 18:54 UTC by Sivasuthan9

2024-06-05 19:05 UTC, chandralegend commented
![screenshot_2024-06-06_at_00 32 46](https://github.com/Jaseci-Labs/jaclang/assets/52673571/e91c6db9-4ffe-4524-8654-05ae7b1fb02c)
![screenshot_2024-06-06_at_00 33 23](https://github.com/Jaseci-Labs/jaclang/assets/52673571/c31a2196-54d7-4fdf-b1be-6c83650b81d3)

2024-06-06 19:43 UTC, marsninja requested changes
Separate workflow for testing streamlit, and I'd move tests folder inside of streamlit folder if possible

2024-06-06 19:43 UTC, marsninja commented on .github/workflows/run_pytest.yml
> +        pip install streamlit-agraph
I'd create this as a separate workflow

2024-06-09 22:46 UTC, marsninja approved these changes

2024-06-09 22:50 UTC, merged