[INPROGRESS]
Jaseci-Labs/jaclang pull request #429
Opened 2024-06-10 13:57 UTC by amadolid

# **Name of PR**

## **Description**

2024-06-19 13:24 UTC, amadolid commented
backup https://github.com/Jaseci-Labs/jaclang/tree/patch/local_jaseci_plugin_backup

2024-06-20 09:23 UTC, marsninja commented on jaclang/cli/cli.py
> +def get_object(id: str, session: str = "") -> dict[str, Any]:
From ChatGPT

Choosing Between object and Any

Use object: When you want to accept any type but still want to maintain some level of type checking and indicate that you don't expect to perform operations that assume a specific type.

Use Any: When you want to explicitly allow any type and operations without any type checking.

2024-06-20 09:26 UTC, marsninja commented on jaclang/cli/cli.py
> +    root: str = "",
is this to support multi users? indexed by root?

2024-06-20 09:44 UTC, amadolid commented on jaclang/cli/cli.py
> +    root: str = "",
technically, yes. The idea is, graph "owner"/root will be the base permission layer for the whole graph regardless if it's associated with a user or not

2024-06-20 14:14 UTC, ypkang requested changes

2024-06-20 14:14 UTC, ypkang commented on jaclang/core/construct.py
> +    def spawn_call(self, walk: WalkerAnchor) -> WalkerArchitype:
This will require change on the parser I think.

2024-06-20 14:14 UTC, ypkang commented on jaclang/core/construct.py
> +    ignores: list[Architype] = field(default_factory=list)
whats the difference between `field(default_factory=list)` and `field(default_factory=lambda: [])`

2024-06-20 14:14 UTC, ypkang commented on jaclang/core/construct.py
> +        return cast(Optional[WalkerAnchor], super().sync(node))
Do we need to store walkers to shelve/DB?

2024-06-20 14:14 UTC, ypkang commented on jaclang/core/construct.py
> +            return walker
Does this block change any actual logic? or just switching from interacting with architype to anchor?

2024-06-20 14:14 UTC, ypkang commented on jaclang/core/construct.py
> +                self._save()
Is the underlying NodeArchitype being saved?

2024-06-20 14:14 UTC, ypkang commented on jaclang/core/construct.py
> +class ContextOptions(TypedDict, total=False):
I wonder if this is neccessary? as opposed to just have the options explicitly laid out in the ExecutionContext module.

2024-06-20 14:14 UTC, ypkang commented on jaclang/plugin/default.py
> +    def get_root() -> NodeArchitype:
This should be `Root` type right?

2024-06-20 14:14 UTC, ypkang commented on jaclang/plugin/default.py
> +        raise Exception(f"Invalid Reference {jroot.ref_id}")
Yeah i don't think we need 478 - 480 if we have the type hint on return to be Root.

2024-06-20 14:14 UTC, ypkang commented on jaclang/plugin/memory.py
> +        """Temporary."""
Let's remember to finish these docstrings before we merge this.

2024-06-20 14:46 UTC, ypkang requested changes

2024-06-20 14:46 UTC, ypkang commented on jaclang/core/construct.py
> +class AnchorAccess(Generic[T]):
Let's call this Permission?

2024-06-21 09:30 UTC, amadolid commented on jaclang/cli/cli.py
> +    jctx = Jac.context("test.session", {"root": root, "entry": node})
ow, this is temporary. Will remove this once PR are finalized
Currently, CLI doesn't work as expected as session argument is not really passed on the function

2024-06-21 09:31 UTC, amadolid commented on jaclang/core/construct.py
> +        if ref_id and (match := GENERIC_ID_REGEX.search(ref_id)):
yup, will update this

2024-06-21 09:31 UTC, amadolid commented on jaclang/core/construct.py
> +        """Return DocAnchor instance if ."""
Will update

2024-06-21 09:32 UTC, amadolid commented on jaclang/core/construct.py
> +        """Retrieve the Architype from db and return."""
Will update

2024-06-21 09:32 UTC, amadolid commented on jaclang/core/construct.py
> +                self._save()
yes, it's always tied up with NodeAnchor.

NodeAnchor from Shelf will always have architype field

2024-06-21 09:35 UTC, amadolid commented on jaclang/core/construct.py
> +class ContextOptions(TypedDict, total=False):
This is to have a overridable JacFeature.context function. Since ExecutionContext might have different __init__ arguments, JacFeature.context will also need to have that. Using ContextOptions will make it easier to override

2024-06-21 09:37 UTC, amadolid commented on jaclang/plugin/default.py
> +    def get_root() -> NodeArchitype:
I actually forgot why I changed this haha

2024-06-21 09:38 UTC, amadolid commented on jaclang/plugin/default.py
> +        raise Exception(f"Invalid Reference {jroot.ref_id}")
will check this

2024-06-21 09:39 UTC, amadolid commented on jaclang/core/construct.py
> +class AnchorAccess(Generic[T]):
We can discuss about this as "Permission" is more like what can you do on the node. While access is more like if you can access it or not.

2024-06-22 05:06 UTC, amadolid commented on test.jac
> +node a {
removed

2024-06-22 07:58 UTC, amadolid commented
migrated to https://github.com/Jaseci-Labs/jaclang/pull/478

2024-06-22 07:58 UTC, closed without merging