check syntax no more explicitly need to call assertXXX
Jaseci-Labs/jaclang pull request #534
Opened 2024-07-26 20:03 UTC by ThakeeNathees

## **Description**

## Jac source
![image](https://github.com/user-attachments/assets/e02a230d-a557-4037-afce-d68c148bc519)

## Generated python source
![image](https://github.com/user-attachments/assets/a1391c27-ab09-434b-a9ad-03ead03fe987)

## Output
![image](https://github.com/user-attachments/assets/ad51d717-224c-4fae-9f03-3f843b9de23d)

2024-07-27 03:21 UTC, ThakeeNathees commented
I think we can go with something like bellow too, recursively but not sure.
```py
test foo {
  check (1==2) and (2 <3);
}
```

```py
assertEqual(1,2) and assertLess(2,3)
```

But this will be for a future improvement and we can mark it as a low priority todo.

2024-08-01 12:22 UTC, marsninja requested changes
few quick things, but this pr is very good!!!

2024-08-01 12:22 UTC, marsninja commented on jaclang/compiler/passes/main/pyast_gen_pass.py
> +                self.clss: ast3.AST | None = clss
cleaner if you use @dataclass

2024-08-01 12:22 UTC, marsninja commented on jaclang/compiler/passes/main/pyast_gen_pass.py
> +            )
I think this would be better if the logic primarily checked Jac AstNode fields instead of python ast node fields. 

This is primarily because the rate of change of jac ast may be slower / more predictable than python when it comes to future python version upgrades. Having a jac ast first based codgen logic then leaving the translation of jac ast to python ast as another conceptual task may help future maintainability.

2024-08-02 14:14 UTC, ThakeeNathees commented on jaclang/compiler/passes/main/pyast_gen_pass.py
> +                self.clss: ast3.AST | None = clss
Done

2024-08-05 15:05 UTC, marsninja approved these changes

2024-08-05 15:06 UTC, merged