chore: Add support for running tests for mtllm plugin
Jaseci-Labs/jaclang pull request #545
Opened 2024-07-30 12:20 UTC by chandralegend

## **Description**

2024-08-05 18:06 UTC, marsninja requested changes

2024-08-05 18:06 UTC, marsninja commented on .github/workflows/run_plugin_tests.yml
> +              run: pytest mtllm
weren't we moving this to mtllm repo?

2024-08-05 18:06 UTC, marsninja commented on .github/workflows/run_plugin_tests.yml
> +              run: pytest mtllm
Also lets create a test that when you try to run an mtllm jac program, that the right errors and triggered.

2024-08-06 03:50 UTC, Jayanaka-98 commented on .github/workflows/run_plugin_tests.yml
> +              run: pytest mtllm
I think we should go for stratergy where MTLLM is always pinned to the latest compatible version of Jac-lang. We can use dependabot https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide to auto generate PRs with updates to the dependancies which we can merge manually to the MTLLM repo.

2024-08-07 17:19 UTC, chandralegend commented on .github/workflows/run_plugin_tests.yml
> +              run: pytest mtllm
Yeah. from next release onword we will pin the jaclang version from latest to next medium change (0.1.0 -> 0.2.0) but at the same time its better to have this job in the plugin test workflow. Its doesn't do any harm and this will allow us to find the breaking time when updating the jaclang.

2024-08-07 17:20 UTC, chandralegend commented on .github/workflows/run_plugin_tests.yml
> +              run: pytest mtllm
Updated the current Tests check the error

2024-08-13 17:55 UTC, marsninja approved these changes

2024-08-13 17:56 UTC, merged