(PR-SERIES-P4) [REFACTOR]: Memory handler
Jaseci-Labs/jaclang pull request #576
Opened 2024-08-16 09:35 UTC by amadolid

2024-08-16 14:27 UTC, ypkang requested changes

2024-08-16 14:27 UTC, ypkang commented on jaclang/runtimelib/architype.py
> -    def populate_edges(self) -> None:
where did this go?

2024-08-16 14:27 UTC, ypkang commented on jaclang/runtimelib/architype.py
> +    hash: int = 0
One benefit is it will make the serializing ancho simpler. We won't need to specifically handle `state`

2024-08-16 14:27 UTC, ypkang commented on jaclang/runtimelib/context.py
> +        self.mem = ShelfStorage(session)
If user doesn't specify session, it should be in memory only i think.

2024-08-16 14:27 UTC, ypkang commented on jaclang/runtimelib/context.py
> -    def get_obj(self, obj_id: UUID) -> Anchor | None:
I think an abstraction at the context level might be useful. For example, if the memory interface changes later, we just need to update this one place, without having to update throughout the codebase.

2024-08-16 14:27 UTC, ypkang commented on jaclang/runtimelib/memory.py
> +        ids: ID | Iterable[ID],
for `find_one`, should this just be a single ID?

2024-08-16 14:27 UTC, ypkang commented on jaclang/runtimelib/memory.py
> +            self.__gc__.add(id)
What is the usage of the `__gc__` list in this scenario?

2024-08-16 14:27 UTC, ypkang commented on jaclang/runtimelib/memory.py
> +        if isinstance(self.__shelf__, Shelf):
I think we can just do `if self.__shelf__` here. It is easier to read. 

Checking for type makes reader think this can be other types.

2024-08-16 14:27 UTC, ypkang commented on jaclang/runtimelib/memory.py
> +            self.__shelf__.sync()
Need to walk through this part.

2024-08-16 15:54 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +    hash: int = 0
there's a reason why I add every mutable on a different class inside Anchors
we can discuss later

2024-08-16 15:57 UTC, amadolid commented on jaclang/runtimelib/context.py
> -    def get_obj(self, obj_id: UUID) -> Anchor | None:
my assumptions is, we will also have

(not exact*)
Jac.get_context()
Jac.get_datasource()

I think ExecutionContext should be holder only (or atleast initializer)

2024-08-16 15:58 UTC, amadolid commented on jaclang/runtimelib/memory.py
> +        ids: ID | Iterable[ID],
it can be multiple id, but find first

2024-08-16 15:58 UTC, amadolid commented on jaclang/runtimelib/memory.py
> +            self.__gc__.add(id)
to be deleted anchors

2024-08-16 15:59 UTC, amadolid commented on jaclang/runtimelib/memory.py
> +        if isinstance(self.__shelf__, Shelf):
make sense. Will update

2024-08-16 16:00 UTC, amadolid commented on jaclang/plugin/default.py
> +                        anchor.destroy()
detach is essentially destroying the edge

destroy calls detach

2024-08-16 16:01 UTC, amadolid commented on jaclang/cli/cli.py
> +        obj = Jac.context().mem.find_one(UUID(node))
it should be Jac.datasource or Jac.get_datasource and this will be included on next PR

Execution should only holds "Context" related functions/attr

2024-08-16 16:02 UTC, amadolid commented on jaclang/plugin/default.py
> +                    (architype := anchor.sync(node))
yup, we can discuss

but in Context, it's very similar in concept how ORM works

2024-08-16 17:51 UTC, amadolid commented on jaclang/runtimelib/memory.py
> +        if isinstance(self.__shelf__, Shelf):
ooow forgot about this.

It's necessary as empty self.__shelf__ will tagged as false similar to dict

2024-08-16 17:52 UTC, amadolid commented on jaclang/runtimelib/memory.py
> +        if isinstance(self.__shelf__, Shelf):
ooow forgot about this.

It's necessary as empty self.\_\_shelf__ will be tagged as false similar to dict

2024-08-17 05:09 UTC, amadolid commented on jaclang/runtimelib/architype.py
> -    def populate_edges(self) -> None:
we don't need this anymore as populate edge also get it one by one
not in bulk

using sync() approach will also do it like this but on demand

2024-08-17 05:11 UTC, amadolid commented on jaclang/runtimelib/context.py
> +        self.mem = ShelfStorage(session)
ShelfStorage is still a Memory if you don't specify a session

2024-08-17 13:06 UTC, marsninja commented on jaclang/cli/cli.py
>          print(f"Object with id {id} not found.")
use logging instead of print here

2024-08-19 15:42 UTC, ypkang requested changes

2024-08-19 15:42 UTC, ypkang commented on jaclang/runtimelib/memory.py
> +        ids: ID | Iterable[ID],
We will have find and find_by_id which just accept a single id with no filte.r

2024-08-19 15:42 UTC, ypkang commented on jaclang/runtimelib/memory.py
> +            self.__shelf__.sync()
This will change.

2024-08-19 15:42 UTC, ypkang commented on jaclang/runtimelib/architype.py
> -    def populate_edges(self) -> None:
This will be back.

2024-08-19 15:42 UTC, ypkang commented on jaclang/runtimelib/architype.py
> -    edge_ids: list[UUID] = field(default_factory=list)
Bring this back for now.

2024-08-19 15:42 UTC, ypkang commented on jaclang/runtimelib/architype.py
> +class AnchorState:
AnchorState will no longer be neccessary.

2024-08-19 17:03 UTC, amadolid commented
backup: https://github.com/Jaseci-Labs/jaclang/tree/pr-series/4-backup

2024-08-19 18:20 UTC, ypkang commented on jaclang/cli/cli.py
>          print(f"Object with id {id} not found.")
@amadolid

2024-08-19 18:20 UTC, ypkang commented on jaclang/runtimelib/architype.py
> +        return hash(self.id)
should we override the hash here? later on, we are calling hash(dump(anchor)). If we don't override it here then we can just call hash(anchor) right?

2024-08-19 18:20 UTC, ypkang commented on jaclang/runtimelib/architype.py
> +                "edge_ids": self.edge_ids + [edge.id for edge in self.edges],
during getstate, edge_ids should always be empty right? Is there a scenario where edge_ids would have value?

2024-08-19 18:49 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +        return hash(self.id)
as far as I remember, current anchor is not hashable and it's required to be overriden to be able to used in set or dict key

2024-08-19 18:50 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +                "edge_ids": self.edge_ids + [edge.id for edge in self.edges],
if you haven't trigger any edge_ref/disconnect and you triggered connect

2024-08-19 18:52 UTC, amadolid commented on jaclang/cli/cli.py
>          print(f"Object with id {id} not found.")
might need to pr it seperately as most of unit test still validates in "print"

2024-08-19 18:54 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +        return hash(self.id)
hash(dump(anchor)) is for different usage as it for including everything inside the anchor while __hash__ is just for hashing anchor's reference

2024-08-22 15:14 UTC, marsninja commented on jaclang/runtimelib/architype.py
> +            self.source_id = None
Based on long discussion with @ypkang , we've converged on moving all logic detecting whether  an anchor is just an ID or should be loaded should live in the anchor class, similar to what you were doing wiht sync, but perhaps in this style (using property and setter):

![image](https://github.com/user-attachments/assets/d2977ed6-5018-4293-a283-3b695f01e316)

2024-08-22 18:52 UTC, ypkang requested changes

2024-08-22 18:52 UTC, ypkang commented on jaclang/runtimelib/architype.py
> +        }
Create a new type PickableAnchor

2024-08-22 18:52 UTC, ypkang commented on jaclang/runtimelib/architype.py
> +            self.source_id = None
load and unload

2024-08-23 09:11 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +        }
need to discuss again as this will include unnecessary fields that's not needed if follow the sync/unsync approach

2024-08-23 09:13 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +            self.source_id = None
this will require every other lazy loaded field to be added as property to.

2024-08-27 15:58 UTC, marsninja approved these changes

2024-08-27 15:59 UTC, merged