(PR-SERIES-P6) [ENHANCEMENT]: Implement Access Validation
Jaseci-Labs/jaclang pull request #583
Opened 2024-08-21 17:32 UTC by amadolid

2024-08-21 21:11 UTC, ypkang requested changes

2024-08-21 21:11 UTC, ypkang commented on jaclang/runtimelib/context.py
> +    def validate_access(self) -> bool:
where is this used?

2024-08-21 21:11 UTC, ypkang commented on jaclang/runtimelib/context.py
> +        ):
Check for Truthiness is enough here?

2024-08-21 21:11 UTC, ypkang commented on jaclang/runtimelib/context.py
> +        return self.__entry__
Need to understand this...

2024-08-21 21:11 UTC, ypkang commented on jaclang/runtimelib/memory.py
> +                    elif not (
I think write access validation should happen at time of modification, instead of at time of writing back to storage. In general, I think if permission fails, we should fail more eagerly. 

Let's discuss.

2024-08-21 21:11 UTC, ypkang commented on jaclang/runtimelib/architype.py
> +        return to.current_access_level
I think this whole function would actually be much simpler if whitelist vs blacklist is not a factor.

2024-08-22 05:47 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +                return val
int might not be that reliable as it can change anytime
AccessLevel type is more reliable but needs to be imported
str is most recommended

2024-08-22 05:48 UTC, amadolid commented on jaclang/plugin/default.py
> +                if _left.has_connect_access(_right):
currently, we just skip/ignore the execution

should we throw exception instead?

2024-08-22 05:49 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +            self.access.roots.whitelist = whitelist
I'm not sure what you mean as it's already part of Access class

2024-08-22 05:55 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +    whitelist: bool = True  # whitelist or blacklist
extra check with `if whitelist` should be negligible while giving more benefits.

whitelist and blacklist should coexists. Neither of the two can do what other can without making it more complex

2024-08-22 05:57 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +            self.disallow_root(root_id, level)
it's pretty straightforward,

allow_root is for allowing the root regardless if it's whitelist or blacklist
similar with disallow_root

it's just it's how it will be saved on access field

2024-08-22 05:57 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +@dataclass(eq=False)
for consistency

it should be similar to generated Architypes

2024-08-22 05:58 UTC, amadolid commented on jaclang/runtimelib/context.py
> +    def validate_access(self) -> bool:
on initial spawn call
cli.enter

2024-08-22 05:59 UTC, amadolid commented on jaclang/runtimelib/context.py
> +        ):
find_by_id returns Anchor
using this approach also add type hinting that is should be a NodeAnchor

2024-08-22 06:00 UTC, amadolid commented on jaclang/runtimelib/context.py
> +        return self.__entry__
Lazy loading entry node as it's not yet available before jac_import

the only available NodeArchitype before jac_import is Root class

2024-08-22 06:03 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +        return to.current_access_level
right now we can't catch it all, if it's a list, dict or custom dataclass we can't detect any manipulation on it

2024-08-22 06:04 UTC, amadolid commented on jaclang/runtimelib/memory.py
> +                    elif not (
right now we can't catch it all, if it's a list, dict or custom dataclass we can't detect any manipulation on it, without adding syntax adjustment

and even if we did, there's always a way or edge case that we can't catch

2024-08-22 06:06 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +    whitelist: bool = True  # whitelist or blacklist
extra check with `if whitelist` should be negligible while giving more benefits.

Both whitelist and blacklist should be supported. Neither of the two can do what other can without making it more complex

2024-08-22 06:07 UTC, amadolid commented on jaclang/runtimelib/architype.py
> +        return to.current_access_level
I will argue that removing blacklist make it simple but make it limited at the same time

2024-08-30 14:52 UTC, ypkang commented on jaclang/plugin/default.py
> +                    and target.architype
Don't we need similar logic for connect?

2024-08-30 14:52 UTC, ypkang commented on jaclang/runtimelib/architype.py
> +                and target.architype
Is this still neccessary? architype is no longer optional right?

2024-08-30 14:52 UTC, ypkang commented on jaclang/runtimelib/architype.py
> +                    and target.has_read_access(source)
This is interesting...do i need access to the target node in order to access the edge connecting to it?

2024-08-30 14:52 UTC, ypkang commented on jaclang/runtimelib/architype.py
> +    _jac_exit_funcs_: ClassVar[list[DSFunc]] = []  # type: ignore[misc]
Not sure about this. @marsninja .

2024-08-31 14:39 UTC, marsninja approved these changes

2024-08-31 14:40 UTC, merged